# Generated by Django 5.2.8 on 2025-12-02 18:57

import django.db.models.deletion
from django.db import migrations, models


def migrar_carreras_a_modelo(apps, schema_editor):
    """Migra los datos de carrera de CharField a ForeignKey"""
    Estudiante = apps.get_model('estudiantes', 'Estudiante')
    Carrera = apps.get_model('estudiantes', 'Carrera')
    
    # Usar raw SQL para leer los valores de carrera directamente de la base de datos
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Obtener todos los estudiantes con sus carreras (como texto)
        cursor.execute("SELECT id, carrera FROM estudiantes_estudiante WHERE carrera IS NOT NULL AND carrera != ''")
        estudiantes_data = cursor.fetchall()
    
    # Crear carreras únicas basadas en los valores existentes
    carreras_creadas = {}
    for estudiante_id, nombre_carrera in estudiantes_data:
        if nombre_carrera:
            # Normalizar el nombre (mayúsculas)
            nombre_normalizado = nombre_carrera.upper().strip()
            if nombre_normalizado and nombre_normalizado not in carreras_creadas:
                carrera, created = Carrera.objects.get_or_create(
                    nombre=nombre_normalizado,
                    defaults={
                        'fija': False,
                        'activa': True,
                    }
                )
                carreras_creadas[nombre_normalizado] = carrera
    
    # Actualizar estudiantes con las carreras correspondientes
    with connection.cursor() as cursor:
        for estudiante_id, nombre_carrera in estudiantes_data:
            if nombre_carrera:
                nombre_normalizado = nombre_carrera.upper().strip()
                if nombre_normalizado in carreras_creadas:
                    carrera = carreras_creadas[nombre_normalizado]
                    cursor.execute(
                        "UPDATE estudiantes_estudiante SET carrera_nueva_id = %s WHERE id = %s",
                        [carrera.id, estudiante_id]
                    )


def revertir_migracion_carreras(apps, schema_editor):
    """Revertir la migración (no necesario, pero requerido)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        # Paso 1: Crear el modelo Carrera
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la carrera')),
                ('fija', models.BooleanField(default=False, help_text='Si está marcada, esta carrera no puede ser modificada ni eliminada', verbose_name='Carrera fija del sistema')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        # Paso 2: Agregar campo temporal carrera_nueva como ForeignKey nullable
        migrations.AddField(
            model_name='estudiante',
            name='carrera_nueva',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_temp', to='estudiantes.carrera', verbose_name='Carrera Nueva'),
        ),
        # Paso 3: Migrar los datos
        migrations.RunPython(migrar_carreras_a_modelo, revertir_migracion_carreras),
        # Paso 4: Eliminar el campo carrera antiguo (CharField)
        migrations.RemoveField(
            model_name='estudiante',
            name='carrera',
        ),
        # Paso 5: Renombrar carrera_nueva a carrera
        migrations.RenameField(
            model_name='estudiante',
            old_name='carrera_nueva',
            new_name='carrera',
        ),
        # Paso 6: Hacer el campo NOT NULL (se hará en la siguiente migración después de insertar carreras fijas)
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código de estudiante'),
        ),
    ]
