# Generated by Django 5.2.8 on 2025-12-02 18:58

import django.db.models.deletion
from django.db import migrations, models


def insertar_carreras_fijas(apps, schema_editor):
    """Inserta las carreras fijas del sistema que no pueden ser modificadas"""
    Carrera = apps.get_model('estudiantes', 'Carrera')
    
    # Lista de carreras fijas del sistema
    carreras_fijas = [
        'INGENIERIA DE SISTEMAS',
        'INGENIERIA DE MECANICA',
        'INGENIERIA DE INDUSTRIAL',
        'INGENIERIA DE MULTIMEDIA',
        'PSICOLOGIA',
        'FISIOTERAPIA',  # Corregido de FSIOTERAPIA
        'DERECHO',
        'MEDICINA',
        'ADMINISTRACIÓN DE EMPRESAS',  # Corregido de ADMINITRACIÓN
        'COMERCIO Y NEGOCIOS INTERNACIONALES',
        'MARKETING DIGITAL',
        'TRABAJO SOCIAL',
    ]
    
    # Insertar o actualizar carreras fijas
    for nombre_carrera in carreras_fijas:
        carrera, created = Carrera.objects.get_or_create(
            nombre=nombre_carrera,
            defaults={
                'fija': True,
                'activa': True,
            }
        )
        # Si la carrera ya existía, actualizarla para marcarla como fija
        if not created:
            carrera.fija = True
            carrera.activa = True
            carrera.save()


def migrar_estudiantes_existentes(apps, schema_editor):
    """Migra estudiantes existentes para usar el nuevo modelo Carrera"""
    # Esta función se ejecuta en reversa, así que no hacemos nada aquí
    pass


def eliminar_carreras_fijas(apps, schema_editor):
    """Elimina las carreras fijas (operación reversa)"""
    Carrera = apps.get_model('estudiantes', 'Carrera')
    Carrera.objects.filter(fija=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_carrera_alter_estudiante_codigo_and_more'),
    ]

    operations = [
        migrations.RunPython(insertar_carreras_fijas, eliminar_carreras_fijas),
        # Hacer el campo carrera NOT NULL después de insertar las carreras
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='estudiantes.carrera', verbose_name='Carrera'),
        ),
    ]
