# Generated by Django 5.2.8 on 2025-11-24 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('asistio', models.BooleanField(default=True, verbose_name='Asistió')),
                ('justificada', models.BooleanField(default=False, verbose_name='Justificada')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='estudiantes.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='materias.materia')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'materia'],
                'unique_together': {('estudiante', 'materia', 'fecha')},
            },
        ),
    ]
